export const INSTITUTIONS_SET_LIST = "INSTITUTIONS_SET_LIST";
export const INSTITUTIONS_SET_CURRENT = "INSTITUTIONS_SET_CURRENT";
export const INSTITUTIONS_SET_FILTERS = "INSTITUTIONS_SET_FILTERS";
export const INSTITUTIONS_SET_LOADING = "INSTITUTIONS_SET_LOADING";
export const INSTITUTIONS_SET_ERROR = "INSTITUTIONS_SET_ERROR";
export const INSTITUTIONS_CLEAR_CURRENT = "INSTITUTIONS_CLEAR_CURRENT";
